# This is a basic workflow to help you get started with Actions

name: Test Action
on:
  workflow_dispatch:
  pull_request:

jobs:
  detect-file-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        base: ${{ github.event_name == 'workflow_dispatch' && 'devel' || '' }}
        filters: |
          test:
            - "test/**"
